// <auto-generated />
using System;
using FIt3d.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FIt3d.DAL.Migrations
{
    [DbContext(typeof(Fit3dDbContext))]
    [Migration("20260309085330_UpdateSeedDataRandomGuidsAndSubscriptionPrice")]
    partial class UpdateSeedDataRandomGuidsAndSubscriptionPrice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fit3d")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FIt3d.DAL.Entities.AIUsageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AIResponse")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("InputData")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("OutputData")
                        .HasColumnType("text");

                    b.Property<int>("ProcessingTimeMs")
                        .HasColumnType("integer");

                    b.Property<int>("RequestType")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserPrompt")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("AIUsageLogs", "fit3d");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Size")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems", "fit3d");

                    b.HasData(
                        new
                        {
                            Id = new Guid("397325b0-8306-47fb-876a-2167c7559b7a"),
                            Color = "Light Blue",
                            CreatedAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d26859fa-798d-4341-b8c7-a2760b4b7522"),
                            Quantity = 1,
                            Size = "L",
                            UserId = new Guid("ef811dc4-971f-4db4-a7cf-72146baaa223")
                        },
                        new
                        {
                            Id = new Guid("641f6db7-0163-4477-a8f5-4eb0064d1a68"),
                            Color = "Black",
                            CreatedAt = new DateTime(2024, 2, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("cb2e4c53-0754-487d-9bc2-8a8e5a5a8ff7"),
                            Quantity = 3,
                            Size = "S",
                            UserId = new Guid("87209cbb-f1b3-45bb-a669-6c6741f6676f")
                        });
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories", "fit3d");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2174b77a-b7fe-4027-90a6-7f8bbd9cc062"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comfortable and stylish t-shirts for everyday wear",
                            DisplayOrder = 1,
                            ImageUrl = "https://example.com/images/categories/tshirts.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "T-Shirts"
                        },
                        new
                        {
                            Id = new Guid("7ef1156c-4412-436c-a7e5-1c0d11b7da91"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quality pants and trousers for all occasions",
                            DisplayOrder = 2,
                            ImageUrl = "https://example.com/images/categories/pants.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Pants"
                        },
                        new
                        {
                            Id = new Guid("f65c980b-aca4-40d4-8179-3acbe852d4fd"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elegant dresses for women",
                            DisplayOrder = 3,
                            ImageUrl = "https://example.com/images/categories/dresses.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dresses"
                        },
                        new
                        {
                            Id = new Guid("d94a333b-96ba-4390-b69c-f6244560b421"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fashion accessories to complete your look",
                            DisplayOrder = 4,
                            ImageUrl = "https://example.com/images/categories/accessories.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigurationData")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EditCount")
                        .HasColumnType("integer");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkedProductsData")
                        .HasColumnType("text");

                    b.Property<int>("MaxEditCount")
                        .HasColumnType("integer");

                    b.Property<string>("ModelFileUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Models", "fit3d");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Orders", "fit3d");

                    b.HasData(
                        new
                        {
                            Id = new Guid("abc47c23-b9b5-495f-ad2d-67d0b8b598a4"),
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeliveredAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountAmount = 50000m,
                            IsDeleted = false,
                            Note = "Please call before delivery",
                            OrderNumber = "ORD-2024-0001",
                            PaymentMethod = "COD",
                            PaymentStatus = 1,
                            ReceiverName = "Nguyen Van A",
                            ReceiverPhone = "0912345678",
                            ShippedAt = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ShippingAddress = "456 Customer Lane, Ha Noi",
                            ShippingFee = 30000m,
                            Status = 4,
                            TotalAmount = 798000m,
                            UserId = new Guid("ef811dc4-971f-4db4-a7cf-72146baaa223")
                        },
                        new
                        {
                            Id = new Guid("861f041d-6422-4734-a615-6ec5a95683ac"),
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderNumber = "ORD-2024-0002",
                            PaymentMethod = "VNPay",
                            PaymentStatus = 1,
                            ReceiverName = "Tran Thi B",
                            ReceiverPhone = "0923456789",
                            ShippingAddress = "789 Shopping Street, Da Nang",
                            ShippingFee = 0m,
                            Status = 2,
                            TotalAmount = 1130000m,
                            UserId = new Guid("87209cbb-f1b3-45bb-a669-6c6741f6676f")
                        });
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Size")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", "fit3d");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f43272b8-57f2-4c6e-8a4a-068a33beffa2"),
                            Color = "White",
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderId = new Guid("abc47c23-b9b5-495f-ad2d-67d0b8b598a4"),
                            ProductId = new Guid("cb2e4c53-0754-487d-9bc2-8a8e5a5a8ff7"),
                            Quantity = 2,
                            Size = "M",
                            TotalPrice = 498000m,
                            UnitPrice = 249000m
                        },
                        new
                        {
                            Id = new Guid("1fb2f6fe-9474-47d1-a0b7-fc70834e3a70"),
                            Color = "Brown",
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderId = new Guid("abc47c23-b9b5-495f-ad2d-67d0b8b598a4"),
                            ProductId = new Guid("78575687-a6be-47fe-9fd9-7fa0dec32b66"),
                            Quantity = 1,
                            TotalPrice = 350000m,
                            UnitPrice = 350000m
                        },
                        new
                        {
                            Id = new Guid("d423bc83-9867-4990-af10-2787d2eec805"),
                            Color = "Blue Wash",
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderId = new Guid("861f041d-6422-4734-a615-6ec5a95683ac"),
                            ProductId = new Guid("3319290d-7bc6-4f66-955e-0bff16902e4f"),
                            Quantity = 1,
                            Size = "30",
                            TotalPrice = 550000m,
                            UnitPrice = 550000m
                        },
                        new
                        {
                            Id = new Guid("e1456c51-45da-45df-a394-80d3ff068395"),
                            Color = "Floral Pink",
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderId = new Guid("861f041d-6422-4734-a615-6ec5a95683ac"),
                            ProductId = new Guid("a2561418-c8a0-4451-9caf-2cc58c625d1e"),
                            Quantity = 1,
                            Size = "M",
                            TotalPrice = 680000m,
                            UnitPrice = 680000m
                        });
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PreviewModelPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", "fit3d");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cb2e4c53-0754-487d-9bc2-8a8e5a5a8ff7"),
                            Brand = "Fit3D",
                            CategoryId = new Guid("2174b77a-b7fe-4027-90a6-7f8bbd9cc062"),
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A timeless classic cotton t-shirt with a comfortable fit. Perfect for casual wear.",
                            ImageUrl = "https://example.com/images/products/tshirt-classic.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Name = "Classic Cotton T-Shirt",
                            Price = 299000m,
                            SKU = "TS-001",
                            SalePrice = 249000m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = new Guid("d26859fa-798d-4341-b8c7-a2760b4b7522"),
                            Brand = "Fit3D",
                            CategoryId = new Guid("2174b77a-b7fe-4027-90a6-7f8bbd9cc062"),
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elegant polo shirt made from premium cotton blend. Great for smart casual occasions.",
                            ImageUrl = "https://example.com/images/products/polo-premium.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Name = "Premium Polo Shirt",
                            Price = 450000m,
                            SKU = "TS-002",
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = new Guid("3319290d-7bc6-4f66-955e-0bff16902e4f"),
                            Brand = "Fit3D Denim",
                            CategoryId = new Guid("7ef1156c-4412-436c-a7e5-1c0d11b7da91"),
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Modern slim fit jeans with stretch for ultimate comfort. Available in multiple washes.",
                            ImageUrl = "https://example.com/images/products/jeans-slim.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsFeatured = false,
                            Name = "Slim Fit Jeans",
                            Price = 650000m,
                            SKU = "PT-001",
                            SalePrice = 550000m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("a2561418-c8a0-4451-9caf-2cc58c625d1e"),
                            Brand = "Fit3D Ladies",
                            CategoryId = new Guid("f65c980b-aca4-40d4-8179-3acbe852d4fd"),
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Beautiful floral print summer dress. Light and breezy fabric perfect for warm days.",
                            ImageUrl = "https://example.com/images/products/dress-floral.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Name = "Floral Summer Dress",
                            Price = 780000m,
                            SKU = "DR-001",
                            SalePrice = 680000m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("78575687-a6be-47fe-9fd9-7fa0dec32b66"),
                            Brand = "Fit3D Accessories",
                            CategoryId = new Guid("d94a333b-96ba-4390-b69c-f6244560b421"),
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Genuine leather belt with classic buckle. Perfect accessory for any outfit.",
                            ImageUrl = "https://example.com/images/products/belt-leather.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsFeatured = false,
                            Name = "Leather Belt",
                            Price = 350000m,
                            SKU = "AC-001",
                            StockQuantity = 60
                        });
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.ProductColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColorCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductColors", "fit3d");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a289b4b2-2cfa-4aea-969a-b53baa3a6ede"),
                            ColorCode = "#FFFFFF",
                            ColorName = "White",
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("cb2e4c53-0754-487d-9bc2-8a8e5a5a8ff7"),
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = new Guid("2fa71da7-5c2f-4f7e-8e92-207d3aa2df92"),
                            ColorCode = "#000000",
                            ColorName = "Black",
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("cb2e4c53-0754-487d-9bc2-8a8e5a5a8ff7"),
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = new Guid("872267f3-eeb6-46ae-82cd-8077aeadabbf"),
                            ColorCode = "#000080",
                            ColorName = "Navy Blue",
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("cb2e4c53-0754-487d-9bc2-8a8e5a5a8ff7"),
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("509b2af9-8024-4dbf-806a-b5880a836088"),
                            ColorCode = "#FFFFFF",
                            ColorName = "White",
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d26859fa-798d-4341-b8c7-a2760b4b7522"),
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = new Guid("29c61d39-039e-485c-99ff-265a024f82c8"),
                            ColorCode = "#ADD8E6",
                            ColorName = "Light Blue",
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d26859fa-798d-4341-b8c7-a2760b4b7522"),
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = new Guid("8ef84190-3522-48da-95af-96735fab3301"),
                            ColorCode = "#FFC0CB",
                            ColorName = "Pink",
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d26859fa-798d-4341-b8c7-a2760b4b7522"),
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = new Guid("ac4541e7-ae1b-42c9-9912-29d77f0a0453"),
                            ColorCode = "#4169E1",
                            ColorName = "Blue Wash",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("3319290d-7bc6-4f66-955e-0bff16902e4f"),
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = new Guid("99955166-1bc8-413c-bb33-c1a16a2269e6"),
                            ColorCode = "#191970",
                            ColorName = "Dark Wash",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("3319290d-7bc6-4f66-955e-0bff16902e4f"),
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = new Guid("f0ed1a32-6a07-486c-ae4c-3648dd7bf4d4"),
                            ColorCode = "#FFB6C1",
                            ColorName = "Floral Pink",
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("a2561418-c8a0-4451-9caf-2cc58c625d1e"),
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("ee72276f-52dd-4400-9402-2b3e2d9f2eb7"),
                            ColorCode = "#87CEEB",
                            ColorName = "Floral Blue",
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("a2561418-c8a0-4451-9caf-2cc58c625d1e"),
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("6493149e-6c21-4f3b-9ae2-40ac2698d7a4"),
                            ColorCode = "#8B4513",
                            ColorName = "Brown",
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("78575687-a6be-47fe-9fd9-7fa0dec32b66"),
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("c29c562c-6432-4add-a1fc-fbbcca40258d"),
                            ColorCode = "#000000",
                            ColorName = "Black",
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("78575687-a6be-47fe-9fd9-7fa0dec32b66"),
                            StockQuantity = 30
                        });
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.ProductSize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSizes", "fit3d");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b476d78-3bb1-436c-afad-9521b8e48f50"),
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("cb2e4c53-0754-487d-9bc2-8a8e5a5a8ff7"),
                            Size = "S",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = new Guid("e626bf6b-d999-459b-9cff-82271cad1b48"),
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("cb2e4c53-0754-487d-9bc2-8a8e5a5a8ff7"),
                            Size = "M",
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("7072a38f-5eda-4d27-8df3-d26aff252d35"),
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("cb2e4c53-0754-487d-9bc2-8a8e5a5a8ff7"),
                            Size = "L",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = new Guid("3a4efbb6-f308-4cae-ba63-3beb600ba00c"),
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("cb2e4c53-0754-487d-9bc2-8a8e5a5a8ff7"),
                            Size = "XL",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = new Guid("4bc01d6a-9083-4c4e-bf05-b46fd6f3d890"),
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d26859fa-798d-4341-b8c7-a2760b4b7522"),
                            Size = "S",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = new Guid("d5bcdd99-b3a6-4c33-9886-ca5e643bf0a1"),
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d26859fa-798d-4341-b8c7-a2760b4b7522"),
                            Size = "M",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = new Guid("873dbef2-761a-4010-8e71-1637b791603d"),
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("d26859fa-798d-4341-b8c7-a2760b4b7522"),
                            Size = "L",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = new Guid("4dbd716c-8099-47ba-9062-97638f61d4e6"),
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("3319290d-7bc6-4f66-955e-0bff16902e4f"),
                            Size = "28",
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = new Guid("8ee03cf8-12ae-4040-933b-8d4fa1893131"),
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("3319290d-7bc6-4f66-955e-0bff16902e4f"),
                            Size = "30",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("5348d1b0-aa23-45d9-980e-bab1eba81b3b"),
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("3319290d-7bc6-4f66-955e-0bff16902e4f"),
                            Size = "32",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("78f7af9d-961b-4ba9-8b20-20ae118b16c6"),
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("3319290d-7bc6-4f66-955e-0bff16902e4f"),
                            Size = "34",
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = new Guid("666c92f7-b4f3-40c0-a8ee-bf49ecf1deef"),
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("a2561418-c8a0-4451-9caf-2cc58c625d1e"),
                            Size = "S",
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = new Guid("5b84b9dc-7523-439d-afd6-d7bdfbde772c"),
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("a2561418-c8a0-4451-9caf-2cc58c625d1e"),
                            Size = "M",
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = new Guid("2f9c198c-f08e-4227-9700-4ec8b06f73ea"),
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("a2561418-c8a0-4451-9caf-2cc58c625d1e"),
                            Size = "L",
                            StockQuantity = 8
                        });
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "fit3d");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AIRequestsResetDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AIRequestsUsedThisMonth")
                        .HasColumnType("integer");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ModelsUsed")
                        .HasColumnType("integer");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PaymentTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubscriptionPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPlanId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions", "fit3d");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("integer");

                    b.Property<bool>("HasAIFeature")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxAIRequestsPerMonth")
                        .HasColumnType("integer");

                    b.Property<int>("MaxEditsPerModel")
                        .HasColumnType("integer");

                    b.Property<int>("MaxModels")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PlanType")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans", "fit3d");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6bbc62a-2662-4160-8b83-44c76aae92ba"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gói Stylist Pro hàng tháng - AI ?? xu?t màu s?c & phong cách, ch?nh s?a model gi?i h?n",
                            DurationInDays = 30,
                            HasAIFeature = true,
                            IsActive = true,
                            IsDeleted = false,
                            MaxAIRequestsPerMonth = 50,
                            MaxEditsPerModel = 10,
                            MaxModels = 5,
                            Name = "Stylist Pro Monthly",
                            PlanType = 0,
                            Price = 99000m
                        },
                        new
                        {
                            Id = new Guid("cffc1e89-46b3-4efa-a6d4-3fbcfe6f3f91"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gói Stylist Pro n?m - Ti?t ki?m 20%, AI ?? xu?t không gi?i h?n, ch?nh s?a model nhi?u h?n",
                            DurationInDays = 365,
                            HasAIFeature = true,
                            IsActive = true,
                            IsDeleted = false,
                            MaxAIRequestsPerMonth = 200,
                            MaxEditsPerModel = 30,
                            MaxModels = 20,
                            Name = "Stylist Pro Yearly",
                            PlanType = 0,
                            Price = 950000m
                        },
                        new
                        {
                            Id = new Guid("9c1b53da-63f7-4b60-9160-9edd5eaafb56"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gói c? b?n cho shop - 50 model ph?i ??, 10 l?n ch?nh s?a/model",
                            DurationInDays = 30,
                            HasAIFeature = false,
                            IsActive = true,
                            IsDeleted = false,
                            MaxAIRequestsPerMonth = 0,
                            MaxEditsPerModel = 10,
                            MaxModels = 50,
                            Name = "B2B Basic",
                            PlanType = 1,
                            Price = 499000m
                        },
                        new
                        {
                            Id = new Guid("8c00ef67-3541-499b-aaf0-7597b9465466"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gói Pro cho shop - 200 model ph?i ??, 20 l?n ch?nh s?a/model, h? tr? ?u tiên",
                            DurationInDays = 30,
                            HasAIFeature = false,
                            IsActive = true,
                            IsDeleted = false,
                            MaxAIRequestsPerMonth = 0,
                            MaxEditsPerModel = 20,
                            MaxModels = 200,
                            Name = "B2B Pro",
                            PlanType = 1,
                            Price = 1490000m
                        },
                        new
                        {
                            Id = new Guid("ef5a64aa-00fb-4b57-a946-869dcf988331"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gói Enterprise cho shop - 1000 model ph?i ??, 50 l?n ch?nh s?a/model, API access",
                            DurationInDays = 30,
                            HasAIFeature = false,
                            IsActive = true,
                            IsDeleted = false,
                            MaxAIRequestsPerMonth = 0,
                            MaxEditsPerModel = 50,
                            MaxModels = 1000,
                            Name = "B2B Enterprise",
                            PlanType = 1,
                            Price = 4990000m
                        },
                        new
                        {
                            Id = new Guid("f5296a48-bd21-4341-a462-50d327d3ee72"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gói c? b?n 100.000 VND/tháng - Tr?i nghi?m tính n?ng AI c? b?n",
                            DurationInDays = 30,
                            HasAIFeature = true,
                            IsActive = true,
                            IsDeleted = false,
                            MaxAIRequestsPerMonth = 20,
                            MaxEditsPerModel = 5,
                            MaxModels = 3,
                            Name = "Gói C? B?n",
                            PlanType = 0,
                            Price = 100000m
                        },
                        new
                        {
                            Id = new Guid("9be6d44f-c0bd-4821-a0f7-657eb75a29fe"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gói nâng cao 200.000 VND/tháng - Tr?i nghi?m ??y ?? tính n?ng AI",
                            DurationInDays = 30,
                            HasAIFeature = true,
                            IsActive = true,
                            IsDeleted = false,
                            MaxAIRequestsPerMonth = 100,
                            MaxEditsPerModel = 20,
                            MaxModels = 10,
                            Name = "Gói Nâng Cao",
                            PlanType = 0,
                            Price = 200000m
                        });
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CheckoutUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentLinkId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TransactionStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions", "fit3d");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("ShopDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ShopName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "fit3d");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef0e2aff-84ad-4a3b-8486-6131eff68548"),
                            Address = "123 Admin Street, Ho Chi Minh City",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@fit3d.com",
                            FullName = "Admin User",
                            IsActive = true,
                            IsDeleted = false,
                            IsVerified = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEJ8g1234567890abcdefghijklmnop",
                            Phone = "0901234567",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("ef811dc4-971f-4db4-a7cf-72146baaa223"),
                            Address = "456 Customer Lane, Ha Noi",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nguyenvana@gmail.com",
                            FullName = "Nguyen Van A",
                            IsActive = true,
                            IsDeleted = false,
                            IsVerified = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEJ8g1234567890abcdefghijklmnop",
                            Phone = "0912345678",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("87209cbb-f1b3-45bb-a669-6c6741f6676f"),
                            Address = "789 Shopping Street, Da Nang",
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tranthib@gmail.com",
                            FullName = "Tran Thi B",
                            IsActive = true,
                            IsDeleted = false,
                            IsVerified = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEJ8g1234567890abcdefghijklmnop",
                            Phone = "0923456789",
                            Role = 0
                        });
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.AIUsageLog", b =>
                {
                    b.HasOne("FIt3d.DAL.Entities.Subscription", "Subscription")
                        .WithMany("AIUsageLogs")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FIt3d.DAL.Entities.User", "User")
                        .WithMany("AIUsageLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.CartItem", b =>
                {
                    b.HasOne("FIt3d.DAL.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FIt3d.DAL.Entities.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Model", b =>
                {
                    b.HasOne("FIt3d.DAL.Entities.Subscription", "Subscription")
                        .WithMany("Models")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Order", b =>
                {
                    b.HasOne("FIt3d.DAL.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.OrderItem", b =>
                {
                    b.HasOne("FIt3d.DAL.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIt3d.DAL.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Product", b =>
                {
                    b.HasOne("FIt3d.DAL.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.ProductColor", b =>
                {
                    b.HasOne("FIt3d.DAL.Entities.Product", "Product")
                        .WithMany("ProductColors")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.ProductSize", b =>
                {
                    b.HasOne("FIt3d.DAL.Entities.Product", "Product")
                        .WithMany("ProductSizes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("FIt3d.DAL.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Subscription", b =>
                {
                    b.HasOne("FIt3d.DAL.Entities.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FIt3d.DAL.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubscriptionPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Transaction", b =>
                {
                    b.HasOne("FIt3d.DAL.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FIt3d.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductColors");

                    b.Navigation("ProductSizes");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Subscription", b =>
                {
                    b.Navigation("AIUsageLogs");

                    b.Navigation("Models");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.User", b =>
                {
                    b.Navigation("AIUsageLogs");

                    b.Navigation("CartItems");

                    b.Navigation("Orders");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
