// <auto-generated />
using System;
using FIt3d.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FIt3d.DAL.Migrations
{
    [DbContext(typeof(Fit3dDbContext))]
    [Migration("20260127152946_AddSubscriptionFeatures")]
    partial class AddSubscriptionFeatures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fit3d")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FIt3d.DAL.Entities.AIUsageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("InputData")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("OutputData")
                        .HasColumnType("text");

                    b.Property<int>("ProcessingTimeMs")
                        .HasColumnType("integer");

                    b.Property<int>("RequestType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("AIUsageLogs", "fit3d");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Size")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems", "fit3d");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ca111111-1111-1111-1111-111111111111"),
                            Color = "Light Blue",
                            CreatedAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("22222222-aaaa-2222-aaaa-222222222222"),
                            Quantity = 1,
                            Size = "L",
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("ca222222-2222-2222-2222-222222222222"),
                            Color = "Black",
                            CreatedAt = new DateTime(2024, 2, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("11111111-aaaa-1111-aaaa-111111111111"),
                            Quantity = 3,
                            Size = "S",
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories", "fit3d");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comfortable and stylish t-shirts for everyday wear",
                            DisplayOrder = 1,
                            ImageUrl = "https://example.com/images/categories/tshirts.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "T-Shirts"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quality pants and trousers for all occasions",
                            DisplayOrder = 2,
                            ImageUrl = "https://example.com/images/categories/pants.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Pants"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elegant dresses for women",
                            DisplayOrder = 3,
                            ImageUrl = "https://example.com/images/categories/dresses.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dresses"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fashion accessories to complete your look",
                            DisplayOrder = 4,
                            ImageUrl = "https://example.com/images/categories/accessories.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigurationData")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EditCount")
                        .HasColumnType("integer");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkedProductsData")
                        .HasColumnType("text");

                    b.Property<int>("MaxEditCount")
                        .HasColumnType("integer");

                    b.Property<string>("ModelFileUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Models", "fit3d");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Orders", "fit3d");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeliveredAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountAmount = 50000m,
                            IsDeleted = false,
                            Note = "Please call before delivery",
                            OrderNumber = "ORD-2024-0001",
                            PaymentMethod = "COD",
                            PaymentStatus = 1,
                            ReceiverName = "Nguyen Van A",
                            ReceiverPhone = "0912345678",
                            ShippedAt = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ShippingAddress = "456 Customer Lane, Ha Noi",
                            ShippingFee = 30000m,
                            Status = 4,
                            TotalAmount = 798000m,
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("bbbb2222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderNumber = "ORD-2024-0002",
                            PaymentMethod = "VNPay",
                            PaymentStatus = 1,
                            ReceiverName = "Tran Thi B",
                            ReceiverPhone = "0923456789",
                            ShippingAddress = "789 Shopping Street, Da Nang",
                            ShippingFee = 0m,
                            Status = 2,
                            TotalAmount = 1130000m,
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Size")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", "fit3d");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01111111-1111-1111-1111-111111111111"),
                            Color = "White",
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            ProductId = new Guid("11111111-aaaa-1111-aaaa-111111111111"),
                            Quantity = 2,
                            Size = "M",
                            TotalPrice = 498000m,
                            UnitPrice = 249000m
                        },
                        new
                        {
                            Id = new Guid("02222222-2222-2222-2222-222222222222"),
                            Color = "Brown",
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            ProductId = new Guid("55555555-dddd-5555-dddd-555555555555"),
                            Quantity = 1,
                            TotalPrice = 350000m,
                            UnitPrice = 350000m
                        },
                        new
                        {
                            Id = new Guid("03333333-3333-3333-3333-333333333333"),
                            Color = "Blue Wash",
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderId = new Guid("bbbb2222-2222-2222-2222-222222222222"),
                            ProductId = new Guid("33333333-bbbb-3333-bbbb-333333333333"),
                            Quantity = 1,
                            Size = "30",
                            TotalPrice = 550000m,
                            UnitPrice = 550000m
                        },
                        new
                        {
                            Id = new Guid("04444444-4444-4444-4444-444444444444"),
                            Color = "Floral Pink",
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderId = new Guid("bbbb2222-2222-2222-2222-222222222222"),
                            ProductId = new Guid("44444444-cccc-4444-cccc-444444444444"),
                            Quantity = 1,
                            Size = "M",
                            TotalPrice = 680000m,
                            UnitPrice = 680000m
                        });
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", "fit3d");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-aaaa-1111-aaaa-111111111111"),
                            Brand = "Fit3D",
                            CategoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A timeless classic cotton t-shirt with a comfortable fit. Perfect for casual wear.",
                            ImageUrl = "https://example.com/images/products/tshirt-classic.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Name = "Classic Cotton T-Shirt",
                            Price = 299000m,
                            SKU = "TS-001",
                            SalePrice = 249000m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = new Guid("22222222-aaaa-2222-aaaa-222222222222"),
                            Brand = "Fit3D",
                            CategoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elegant polo shirt made from premium cotton blend. Great for smart casual occasions.",
                            ImageUrl = "https://example.com/images/products/polo-premium.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Name = "Premium Polo Shirt",
                            Price = 450000m,
                            SKU = "TS-002",
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = new Guid("33333333-bbbb-3333-bbbb-333333333333"),
                            Brand = "Fit3D Denim",
                            CategoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Modern slim fit jeans with stretch for ultimate comfort. Available in multiple washes.",
                            ImageUrl = "https://example.com/images/products/jeans-slim.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsFeatured = false,
                            Name = "Slim Fit Jeans",
                            Price = 650000m,
                            SKU = "PT-001",
                            SalePrice = 550000m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("44444444-cccc-4444-cccc-444444444444"),
                            Brand = "Fit3D Ladies",
                            CategoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Beautiful floral print summer dress. Light and breezy fabric perfect for warm days.",
                            ImageUrl = "https://example.com/images/products/dress-floral.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Name = "Floral Summer Dress",
                            Price = 780000m,
                            SKU = "DR-001",
                            SalePrice = 680000m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("55555555-dddd-5555-dddd-555555555555"),
                            Brand = "Fit3D Accessories",
                            CategoryId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Genuine leather belt with classic buckle. Perfect accessory for any outfit.",
                            ImageUrl = "https://example.com/images/products/belt-leather.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsFeatured = false,
                            Name = "Leather Belt",
                            Price = 350000m,
                            SKU = "AC-001",
                            StockQuantity = 60
                        });
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.ProductColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColorCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductColors", "fit3d");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1111111-1111-1111-1111-111111111111"),
                            ColorCode = "#FFFFFF",
                            ColorName = "White",
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("11111111-aaaa-1111-aaaa-111111111111"),
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = new Guid("e2222222-2222-2222-2222-222222222222"),
                            ColorCode = "#000000",
                            ColorName = "Black",
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("11111111-aaaa-1111-aaaa-111111111111"),
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = new Guid("e3333333-3333-3333-3333-333333333333"),
                            ColorCode = "#000080",
                            ColorName = "Navy Blue",
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("11111111-aaaa-1111-aaaa-111111111111"),
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("f1111111-1111-1111-1111-111111111111"),
                            ColorCode = "#FFFFFF",
                            ColorName = "White",
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("22222222-aaaa-2222-aaaa-222222222222"),
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = new Guid("f2222222-2222-2222-2222-222222222222"),
                            ColorCode = "#ADD8E6",
                            ColorName = "Light Blue",
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("22222222-aaaa-2222-aaaa-222222222222"),
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = new Guid("f3333333-3333-3333-3333-333333333333"),
                            ColorCode = "#FFC0CB",
                            ColorName = "Pink",
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("22222222-aaaa-2222-aaaa-222222222222"),
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-1111-1111-111111111111"),
                            ColorCode = "#4169E1",
                            ColorName = "Blue Wash",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("33333333-bbbb-3333-bbbb-333333333333"),
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-1111-1111-111111111111"),
                            ColorCode = "#191970",
                            ColorName = "Dark Wash",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("33333333-bbbb-3333-bbbb-333333333333"),
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = new Guid("33333333-2222-1111-1111-111111111111"),
                            ColorCode = "#FFB6C1",
                            ColorName = "Floral Pink",
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("44444444-cccc-4444-cccc-444444444444"),
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("44444444-2222-1111-1111-111111111111"),
                            ColorCode = "#87CEEB",
                            ColorName = "Floral Blue",
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("44444444-cccc-4444-cccc-444444444444"),
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("55555555-2222-1111-1111-111111111111"),
                            ColorCode = "#8B4513",
                            ColorName = "Brown",
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("55555555-dddd-5555-dddd-555555555555"),
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("66666666-2222-1111-1111-111111111111"),
                            ColorCode = "#000000",
                            ColorName = "Black",
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("55555555-dddd-5555-dddd-555555555555"),
                            StockQuantity = 30
                        });
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.ProductSize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSizes", "fit3d");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("11111111-aaaa-1111-aaaa-111111111111"),
                            Size = "S",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("11111111-aaaa-1111-aaaa-111111111111"),
                            Size = "M",
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("11111111-aaaa-1111-aaaa-111111111111"),
                            Size = "L",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("11111111-aaaa-1111-aaaa-111111111111"),
                            Size = "XL",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("22222222-aaaa-2222-aaaa-222222222222"),
                            Size = "S",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("22222222-aaaa-2222-aaaa-222222222222"),
                            Size = "M",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = new Guid("b3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("22222222-aaaa-2222-aaaa-222222222222"),
                            Size = "L",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("33333333-bbbb-3333-bbbb-333333333333"),
                            Size = "28",
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = new Guid("c2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("33333333-bbbb-3333-bbbb-333333333333"),
                            Size = "30",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("33333333-bbbb-3333-bbbb-333333333333"),
                            Size = "32",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("c4444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("33333333-bbbb-3333-bbbb-333333333333"),
                            Size = "34",
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = new Guid("d1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("44444444-cccc-4444-cccc-444444444444"),
                            Size = "S",
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = new Guid("d2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("44444444-cccc-4444-cccc-444444444444"),
                            Size = "M",
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = new Guid("d3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("44444444-cccc-4444-cccc-444444444444"),
                            Size = "L",
                            StockQuantity = 8
                        });
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AIRequestsResetDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AIRequestsUsedThisMonth")
                        .HasColumnType("integer");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ModelsUsed")
                        .HasColumnType("integer");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PaymentTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubscriptionPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPlanId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions", "fit3d");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("integer");

                    b.Property<bool>("HasAIFeature")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxAIRequestsPerMonth")
                        .HasColumnType("integer");

                    b.Property<int>("MaxEditsPerModel")
                        .HasColumnType("integer");

                    b.Property<int>("MaxModels")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PlanType")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans", "fit3d");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeeeeeee-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gói Stylist Pro hàng tháng - AI ?? xu?t màu s?c & phong cách, ch?nh s?a model gi?i h?n",
                            DurationInDays = 30,
                            HasAIFeature = true,
                            IsActive = true,
                            IsDeleted = false,
                            MaxAIRequestsPerMonth = 50,
                            MaxEditsPerModel = 10,
                            MaxModels = 5,
                            Name = "Stylist Pro Monthly",
                            PlanType = 0,
                            Price = 99000m
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gói Stylist Pro n?m - Ti?t ki?m 20%, AI ?? xu?t không gi?i h?n, ch?nh s?a model nhi?u h?n",
                            DurationInDays = 365,
                            HasAIFeature = true,
                            IsActive = true,
                            IsDeleted = false,
                            MaxAIRequestsPerMonth = 200,
                            MaxEditsPerModel = 30,
                            MaxModels = 20,
                            Name = "Stylist Pro Yearly",
                            PlanType = 0,
                            Price = 950000m
                        },
                        new
                        {
                            Id = new Guid("ffffffff-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gói c? b?n cho shop - 50 model ph?i ??, 10 l?n ch?nh s?a/model",
                            DurationInDays = 30,
                            HasAIFeature = false,
                            IsActive = true,
                            IsDeleted = false,
                            MaxAIRequestsPerMonth = 0,
                            MaxEditsPerModel = 10,
                            MaxModels = 50,
                            Name = "B2B Basic",
                            PlanType = 1,
                            Price = 499000m
                        },
                        new
                        {
                            Id = new Guid("ffffffff-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gói Pro cho shop - 200 model ph?i ??, 20 l?n ch?nh s?a/model, h? tr? ?u tiên",
                            DurationInDays = 30,
                            HasAIFeature = false,
                            IsActive = true,
                            IsDeleted = false,
                            MaxAIRequestsPerMonth = 0,
                            MaxEditsPerModel = 20,
                            MaxModels = 200,
                            Name = "B2B Pro",
                            PlanType = 1,
                            Price = 1490000m
                        },
                        new
                        {
                            Id = new Guid("ffffffff-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gói Enterprise cho shop - 1000 model ph?i ??, 50 l?n ch?nh s?a/model, API access",
                            DurationInDays = 30,
                            HasAIFeature = false,
                            IsActive = true,
                            IsDeleted = false,
                            MaxAIRequestsPerMonth = 0,
                            MaxEditsPerModel = 50,
                            MaxModels = 1000,
                            Name = "B2B Enterprise",
                            PlanType = 1,
                            Price = 4990000m
                        });
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("ShopDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ShopName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "fit3d");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Address = "123 Admin Street, Ho Chi Minh City",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@fit3d.com",
                            FullName = "Admin User",
                            IsActive = true,
                            IsDeleted = false,
                            IsVerified = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEJ8g1234567890abcdefghijklmnop",
                            Phone = "0901234567",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Address = "456 Customer Lane, Ha Noi",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nguyenvana@gmail.com",
                            FullName = "Nguyen Van A",
                            IsActive = true,
                            IsDeleted = false,
                            IsVerified = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEJ8g1234567890abcdefghijklmnop",
                            Phone = "0912345678",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Address = "789 Shopping Street, Da Nang",
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tranthib@gmail.com",
                            FullName = "Tran Thi B",
                            IsActive = true,
                            IsDeleted = false,
                            IsVerified = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEJ8g1234567890abcdefghijklmnop",
                            Phone = "0923456789",
                            Role = 0
                        });
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.AIUsageLog", b =>
                {
                    b.HasOne("FIt3d.DAL.Entities.Subscription", "Subscription")
                        .WithMany("AIUsageLogs")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.CartItem", b =>
                {
                    b.HasOne("FIt3d.DAL.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FIt3d.DAL.Entities.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Model", b =>
                {
                    b.HasOne("FIt3d.DAL.Entities.Subscription", "Subscription")
                        .WithMany("Models")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Order", b =>
                {
                    b.HasOne("FIt3d.DAL.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.OrderItem", b =>
                {
                    b.HasOne("FIt3d.DAL.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIt3d.DAL.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Product", b =>
                {
                    b.HasOne("FIt3d.DAL.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.ProductColor", b =>
                {
                    b.HasOne("FIt3d.DAL.Entities.Product", "Product")
                        .WithMany("ProductColors")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.ProductSize", b =>
                {
                    b.HasOne("FIt3d.DAL.Entities.Product", "Product")
                        .WithMany("ProductSizes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Subscription", b =>
                {
                    b.HasOne("FIt3d.DAL.Entities.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FIt3d.DAL.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubscriptionPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductColors");

                    b.Navigation("ProductSizes");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.Subscription", b =>
                {
                    b.Navigation("AIUsageLogs");

                    b.Navigation("Models");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("FIt3d.DAL.Entities.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
